#! /bin/sh
################################################################
# 
# Archivo de configuracion de BSPWM
# Ubicación: ~/.config/bspwm/bspwmrc
# Autor: Yandri Loor 
#
################################################################

# Iniciar atajos de teclado
pgrep -x > /dev/null || sxhkd &

# Bordes de ventana
bspc config border_width                        1
bspc config window_gap                          4

#-------------------------
# Colores de los bordes
#-------------------------

# Bordes normales y activos
bspc config normal_border_color          "#2e2e2e"  # ventana inactiva
bspc config focused_border_color         "#ffb52a"  # ventana con foco
bspc config active_border_color          "#4c4c4c"  # ventana activa pero no enfocada

# Ventanas bloqueadas
bspc config focused_locked_border_color  "#3a3a3a"
bspc config normal_locked_border_color   "#1f1f1f"
bspc config active_locked_border_color   "#3f3f3f"

# Ventanas urgentes
bspc config urgent_border_color          "#ac4142"  # rojo para notificaciones

# Preselección y feedback
bspc config presel_border_color          "#6a9fb5"  # azul claro
bspc config presel_feedback_color        "#6a9fb5"

# Ventanas privadas
bspc config focused_private_border_color "#5a3e85"
bspc config active_private_border_color  "#4b3270"
bspc config normal_private_border_color  "#3b2655"

# División de ventanas
bspc config split_ratio                         0.50
bspc config borderless_monocle                  true
bspc config gapless_monocle                     true

# Escritorios por monitor
bspc monitor -d 1 2 
#bspc monitor -d   


# Padding y monocle (pantalla completa)
bspc config borderless_monocle                  true
bspc config gapless_monocle                     false
bspc config paddingless_monocle                 false
bspc config single_monocle                      false
bspc config top_padding                         0
bspc config right_padding                       0
bspc config bottom_padding                      0
bspc config left_padding                        0
bspc config auto_alternate                      false
bspc config auto_cancel                         true

# Foco y seguimiento del puntero
bspc config history_aware_focus                 true
bspc config focus_by_distance                   true
bspc config pointer_follows_monitor             true
bspc config pointer_follows_focus               false
bspc config focus_follows_pointer               false

# Reglas de ventanas
bspc rule -r *:*

bspc rule -a mpv state=floating border=off
bspc rule -a feh state=floating border=off

bspc rule -a Gvim state=floating
bspc rule -a Hangouts state=floating
bspc rule -a Yad state=floating
bspc rule -a sys_message state=floating
bspc rule -a Blueman-manager state=floating rectangle=550x250+1365+22
bspc rule -a Nm-connection-editor state=floating rectangle=550x250+1365+22


# Reglas para ventanas flotantes de mantenimiento
bspc rule -a Alacritty state=floating center=on sticky=on

# Fondo de pantalla
feh --bg-scale "$HOME/imagenes/wallpaper-2.jpg"

# Inicios
~/.config/bspwm_lemonbar/bar.sh &
nm-applet --indicator &

dunst -c ~/.config/dunst/dunstrc &
xss-lock lockscreen &
sleep 0.5;xset s activate &

