#############################################################
# Archivo: ~/.config/gtk-3.0/settings.ini
# Descripción: Configuración del tema para instalaciones GTK
# Autor: Yandri Loor
# Última modificación: 24 de Septiembre del 2025
#############################################################

[Settings]
gtk-theme-name=Arc-Dark
gtk-icon-theme-name=Papirus-Dark
gtk-font-name=JetBrains Mono 10

